postgres:
  username: trader
  password:
  host: postres.hostname.com
  port: 12345
  database: trader


shoonya:
  Trader-V2-User:
    user: 'User'
    pwd: 'Password'
    vc: 'User_U'
    apikey: 'API-key'
    imei: 'abc1234'
    token: token
    expiry_date: 2023-01-01
